// AUTO-GENERATED by scripts/generate_scene_manifest.py — do not edit manually

export interface SceneEntry {
  id: string;
  compId: string;
  videoFile: string;
  width: number;
  height: number;
  fps: number;
  durationInFrames: number;
}

// Replace with your own scene manifest entries after running the generation script.
// Example format shown below:
export const SCENE_MANIFEST: SceneEntry[] = [
  { id: "scene_01", compId: "Scene01Example", videoFile: "vsl/scene_01_example.mp4", width: 1080, height: 1920, fps: 30, durationInFrames: 150 },
  { id: "scene_02", compId: "Scene02Example", videoFile: "vsl/scene_02_example.mp4", width: 1080, height: 1920, fps: 30, durationInFrames: 150 },
  { id: "scene_03", compId: "Scene03Example", videoFile: "vsl/scene_03_example.mp4", width: 1080, height: 1920, fps: 30, durationInFrames: 150 },
];
